-- Extend model metrics with additional fields

ALTER TABLE ml_models
ADD COLUMN IF NOT EXISTS precision DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS recall DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS f1_score DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS training_time BIGINT,
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'TRAINING',
ADD COLUMN IF NOT EXISTS confusion_matrix TEXT,
ADD COLUMN IF NOT EXISTS roc_curve_data TEXT;

